### ISSUE TITLE
config.xml error (config.xml empty)

### ISSUE THREAD

**Issue by Altycoder** [linuxserver/docker-lidarr#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been using this Lidarr container for years, now at startup the container generates the following error repeatedly:

```
^
/config/config.xml:1.1: Document is empty
^
/config/config.xml:1.1: Document is empty
^
/config/config.xml:1.1: Document is empty
^
/config/config.xml:1.1: Document is empty
```

### Expected Behavior

Lidarr container starts normally and is accessible on port 8686

### Steps To Reproduce

Start container, /config/config.xml is empty

### Environment

```markdown
- OS: Arch Linux, LTS Kernel
- How docker service was installed: from Arch repo
```

### CPU architecture

x86-64

### Docker creation

```bash
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${DOCKER_DIR}/lidarr:/config
      - /mnt/btrfs_raid/Backup/Music/mp3:/music
      - /mnt/btrfs_raid/Backup/torrents:/downloads
    restart: unless-stopped
```

### Container logs

```bash
Log too long to paste here, can be downloaded from dropbox here:

https://www.dropbox.com/scl/fi/3nqgwib9hkcza6b21yrsf/lidarr.txt?rlkey=trpwxy7o7yvxl18gu1kbnc1jw&dl=0
```

**Comment by Altycoder** [comment]
Managed to hack together a new config.xml by modifying the same file copied from Sonarr, but not sure why this happened in the first place?

**Comment by j0nnymoe** [comment]
You'd want to be pulling the config.xml - it might've got corrupt by an unsafe shutdown or something.

**Comment by Altycoder** [comment]
Closed by re-creating from a copy from Sonarr
