### ISSUE TITLE
Bump libChromaPrint-tools to 1.4.3

### ISSUE THREAD

**Issue by Qstick** [linuxserver/docker-lidarr#13]
while Lidarr works with older versions, we would prefer to work with 1.4.3 or newer.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
We'll likely rebase to bionic soon, which will bump it from the repo.

But we have to rebase the whole mono image and figure out pinning certain versions in the process.

**Comment by homerr** [comment]
Resolved in #15 👍
