### ISSUE TITLE
Download folder reported as "not appear to exist" but does exist.

### ISSUE THREAD

**Issue by antipiot** [linuxserver/docker-lidarr#20]
Lidarr seems not process download folder due to a configuration error;
Lidarr report download folder is not existing but is connecting to another docker with mapped folders:

`You are using docker; download client Deluge places downloads in /downloads/finished but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.`

It obliviously does not exist :-)

I use Lidarr connected to Deluge: both on docker

On deluge:  download folder is mapped as:
/sharedfolders/share/Torrent/ : /download

Default download folder is /download/finished (i use labels)

On Lidarr:download folder is mapped as:
/sharedfolders/share/Torrent/lidarr : /download

Any hint?

**Comment by j0nnymoe** [comment]
`/download` needs to point to the same folder.
