### ISSUE TITLE
Lidarr Lost it's connect to the backend on Windows 10

### ISSUE THREAD

**Issue by rudyolph** [linuxserver/docker-lidarr#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Start container and application should load and stay running successfully.

## Current Behavior
After starting the container an error message will pop up saying:

Connection Lost
Lidarr has lost it's connection to the backend and will need to be reloaded to restore functionality.
Lidarr will try to connect automatically, or you can click reload below.

## Steps to Reproduce

1. Install Docker for Windows on Window 10
2. Docker pull the latest or nightly image 
3. Start the container
4. Navigate to the app
5. Let is sit for 5-10 minutes
6. Read error msg

## Environment
Windows 10     
x86_64
Docker service Docker for Windows
Using Docker-compose ran the following configuration for startup     
  lidarr:
    image: linuxserver/lidarr:preview
    container_name: lidarr
    environment:
      - TZ=America/New_York
    volumes:
      - M:/DockerVolumes/lidarr/config:/config
      - M:/music:/music
      - M:/Downloads:/downloads
    ports:
      - 14306:8686
    restart: unless-stopped

**Comment by j0nnymoe** [comment]
I would say this is an oddity due to using docker on windows. We don't test our images on Windows nor so we support it as a platform for our containers. It's more of a YMMV if using our containers on anything other than Linux.
