### ISSUE TITLE
Artifact locations changed

### ISSUE THREAD

**Issue by volcomism** [linuxserver/docker-lidarr#3]
Looks like the artifacts for lidarr have changed:

`ERROR: Service 'lidarr' failed to build: The command '/bin/sh -c echo "**** install jq ****" &&  apt-get update &&  apt-
get install -y  jq &&  echo "**** install lidarr ****" &&  mkdir -p /app/lidarr &&  lidarr_url=$(curl "https://services.
lidarr.audio/v1/update/${LIDARR_BRANCH}/changes?os=linux"       | jq -r '.[0].url') &&   curl -o  /tmp/lidarr.tar.gz -L
"${lidarr_url}" &&  tar ixzf  /tmp/lidarr.tar.gz -C     /app/lidarr --strip-components=1 &&  echo "**** cleanup ****" &&
  rm -rf        /tmp/*  /var/lib/apt/lists/*    /var/tmp/*' returned a non-zero code: 4`

New artifacts are now located here, however there's no static URL to download - so a grep for the branch name will be needed via API
https://ci.appveyor.com/project/Lidarr/lidarr/build/artifacts

Trying to find a nice solution, but thought I'd post the issue here prior.

**Comment by aptalca** [comment]
#4 
new image is pulling the beta releases from github
