### ISSUE TITLE
Not working on synology

### ISSUE THREAD

**Issue by Romquenin** [linuxserver/docker-lidarr#5]
Hello and thank you for your work, this new docker feature looks awsome. 

Unfortunately i can't manage to make it works on my synology ds1513+.

The log is showing error with "Mono is not running with --debug switch" 
![screenshot_20180523-100937](https://user-images.githubusercontent.com/34734431/40411960-3d626e6e-5e72-11e8-88ae-5e2a427b78c5.png)

Here are some of my settings:
![screenshot_20180523-101023](https://user-images.githubusercontent.com/34734431/40412045-80184008-5e72-11e8-9749-69841a59b946.png)

I don't understand what im doing wrong. 

Thanks.

**Comment by Romquenin** [comment]
Hello, thanks for your answer.

I haven't made any settings for PUIG/PGID. It's new for me i don't know
how, never edited this for any of my conteiner.

Could you explain me how ?

Thanks.

**Comment by j0nnymoe** [comment]
These are environment variables. I have no experience with setting up containers on Synology hardware but you'll need to add these under the `Enviroments` Tab. You need to set them to a user id that has read/write access to the folders you are setting.

**Comment by Romquenin** [comment]
Ok, I will try to do this later today.

Thanks.

**Comment by jrozelle** [comment]
Hello. Same here, with PGID and PUID correctly entered (same as Sonarr & Radarr).
Any idea ? Thx !

**Comment by thelamer** [comment]
Those logs indicate the application is running , what are your port forwarding settings and what happens in your web browser when you try to access that port?

**Comment by homerr** [comment]
Supposing this is a stale issue so closing it. Please comment if the issue persisted and we can investigate further.
