### ISSUE TITLE
When clicking on Settings / General an "Unable to load General settings" error is displayed instead of the general settings page.

### ISSUE THREAD

**Issue by amatriain** [linuxserver/docker-lidarr#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

-----------------------------

## Expected Behavior
The General Settings page should be displayed.

## Current Behavior
An "Unable to load General settings" error is displayed.

![108057839-75730200-7053-11eb-94d5-3c2f7dd7868c](https://user-images.githubusercontent.com/1439986/108903723-eb600600-761d-11eb-85a1-19a1fbe9a8a0.png)

## Steps to Reproduce

1. Click on Settings.
2. Click on General.
3. An error appears

## Environment
**OS:** arch linux, 5.4.97-1-lts kernel
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker hub repo. 

## Command used to create docker container (run/create/compose/screenshot)

Used this docker-compose.yml : https://pastebin.com/winr4V4j

## Docker logs

Logs when reproducing the error here:

https://pastebin.com/JX8FX0Jv

**Comment by amatriain** [comment]
It's been suggested in the Lidarr support subreddit (here: https://www.reddit.com/r/Lidarr/comments/lqjbvb/unable_to_load_general_settings_error/gogydpt/ ) that the problem is a line like this in config.xml:

```
<UpdateMechanism>Docker</UpdateMechanism>
```

I've confirmed that removing that line and restarting the container fixes the bug.

**Comment by aptalca** [comment]
We don't put that into config.xml. We put that into a `package_info` file that lidarr processes and does whatever it needs to do: https://github.com/linuxserver/docker-lidarr/blob/master/Dockerfile#L35

That setting should disable gui updates so you only update via updating the docker image.

If that's not working, it should be reported upstream to lidarr.
