### ISSUE TITLE
Project_logo url in readme-vars.yml is incorrect and logo cannot be found

### ISSUE THREAD

**Issue by technorabilia** [linuxserver/docker-lidarr#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Project_logo url in readme-vars.yml should result in valid logo.

## Current Behavior
Project_logo url in readme-vars.yml is incorrect and logo cannot be found.

## Steps to Reproduce
Open the project_logo url in the browser.

## Environment
All.

## Command used to create docker container (run/create/compose/screenshot)
Does not apply.

## Docker logs
Does not apply.

**Comment by aptalca** [comment]
It loads just fine both when opened directly and in the readme of this repo, which uses that url.

Also please stop opening countless (almost) duplicate issues.

Feel free to drop by discord or discourse as explained in the readme template

**Comment by technorabilia** [comment]
@aptalca 
True, but it doesn't open on https://hub.docker.com/r/linuxserver/lidarr.

I guess that is the difference between blob and raw.
<img src="https://github.com/lidarr/Lidarr/blob/develop/Logo/400.png">
vs.
<img src="https://github.com/lidarr/Lidarr/raw/develop/Logo/400.png" >

It should be raw. Not blob.

**Comment by j0nnymoe** [comment]
I mean, if you'd mentioned that originally, it might've made a lot more sense...

**Comment by technorabilia** [comment]
@j0nnymoe 
Sorry about that.
I am generating templates based on project readme-vars.yml info and I was looking at in total ~10 incorrect logo's for all projects.
Yesterday I reported a few of them with the same bug report. I didn't realize that this one was a bit more complex.
So in this case the project_logo url in readme-vars.yml should point to the raw url and not the blob url. This will make sure the logo is displayed correctly on Docker Hub etc.
