### ISSUE TITLE
[Feature Request] beets implemented in the docker

### ISSUE THREAD

**Issue by JohanSF** [linuxserver/docker-lidarr#6]
Dear Linuxserver,

This is just a request for you to add beets to this docker as it would greatly benefit by it. It would let users use the Connect function with a custom script to autotag albums after import.

Regards, Johan

**Comment by sparklyballs** [comment]
https://github.com/linuxserver/docker-beets

we already have a beets image

**Comment by si0972** [comment]
He wants a way to use beets with lidarr imports, wich in the best case, happens in the same docker.

**Comment by sparklyballs** [comment]
best case for who ? 

it adds unnecessary complexity to the image

i call nzbtomedia script between sabnzbd and medusa docker images (not to re-encode which i've never seen the point of) to handle failed downloads


you can call beets docker from a script which i do with the following

`#!/bin/bash

for extension in \
{accurip,aif,avi,bmp,css,cue,exe,html,info,jpeg,jpg,js,log,m3u,mkv,mov,nfo,pdf,plist,png,sfv,tif,tiff,txt,vob,xml}; \
do

find /mnt/user/Music/Downloads -iname "*.${extension}" -exec rm -f '{}' +

done

docker restart beets
sleep 5s
docker exec -it -u abc beets /bin/bash -c 'beet import /downloads'`

with some additional coding to handle spurious files that may be present with any downloads etc

**Comment by JohanSF** [comment]
Do I need a special volume mapping i lidarr and/or beets to do what you are doing here? As Lidarr does not know what the "docker" command is out of the box.

**Comment by JohanSF** [comment]
May I ask what your connection in Lidarr looks like, and the mappings in unRaid to make this work? Would appreciate it much and bypassers would too I think.

**Comment by sparklyballs** [comment]
i don't use lidarr and didn't say that

i was merely saying you can run beets via a bash script

**Comment by hellmind** [comment]
you cant, the only way to connect beets is to ssh the host. (lidarr docker doesnt got ssh )
