### ISSUE TITLE
Root folder mapped, but it's not seen for imports

### ISSUE THREAD

**Issue by jaysgrant** [linuxserver/docker-lidarr#65]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Root folder is mapped, but is not showing up on the import screen.

![Screenshot from 2021-12-01 21-42-36](https://user-images.githubusercontent.com/33356568/144349735-4a8cba53-ae1d-4e2c-966f-424ce6bb197e.png)

![Screenshot from 2021-12-01 21-43-42](https://user-images.githubusercontent.com/33356568/144349750-43b4560b-2dea-4624-ac1d-9d59ef3f4d6d.png)

I am deploying it via docker-compose. The ID output on the host is 1000 for both the user, and group. I am passing this via environment variables in my docker-compose file. The docker compose entry is as follows.

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - UMASK=022
      - DOCKER_MODS=linuxserver/mods:lidarr-flac2mp3
    volumes:
      - ./lidarr:/config:rw
      - /home/coreadmin/media:/media:rw
      - /home/coreadmin/media/downloads:/downloads:rw
      - ./shared:/shared:rw
    ports:
      - 8686:8686
    restart: unless-stopped

I am able to see, and manipulate the folder mapped for the music library via a shell from within the container.

The activity in the lower left corner does appear to scan through all files, but nothing shows up as able to import. All media is .mp3, and flac.

------------------------------

## Expected Behavior

Existing library is expected to be imported

## Current Behavior

Existing library is not imported

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS: Ubuntu 20.04 Server
**CPU architecture:** x86_64
**How docker service was installed:**

## Docker logs

[lidarr.log](https://github.com/linuxserver/docker-lidarr/files/7638700/lidarr.log)

**Comment by aptalca** [comment]
Most likely permissions. Make sure that folder and its contents are owned by 1000 on host

**Comment by jaysgrant** [comment]
> Most likely permissions. Make sure that folder and its contents are owned by 1000 on host

I have, the user, and group each associated with the id of 1000 are the owners of the whole directory tree.

**Comment by drizuid** [comment]
remove `/home/coreadmin/media/downloads:/downloads:rw` from your volumes, your download path inside the container will simply be /media/downloads

dont mount things inside other things like that
```
- /home/coreadmin/media:/media:rw
- /home/coreadmin/media/downloads:/downloads:rw   <-- bad
```

once you try this, let us know the results.
