### ISSUE TITLE
Files and folders with names containing strange characters such â€™

### ISSUE THREAD

**Issue by diegomontanaduarte** [linuxserver/docker-lidarr#68]
Using Unraid app (Docker), when I'm adding a new album to Lidarr the files and folders names are containing strange characters, sample below

![image](https://user-images.githubusercontent.com/2682853/147587336-2e997982-b0bd-4aa2-92b6-c2f8350b83f5.png)

It seems correlated with OS character encoding since Lidarr is getting the correct names.

![image](https://user-images.githubusercontent.com/2682853/147587376-1a744b20-55ce-4824-9247-ee5ec583e949.png)

**Comment by TheSpad** [comment]
You are likely storing your files on a remote volume mounted with incorrect character encoding.

**Comment by diegomontanaduarte** [comment]
@TheSpad I'm unsure I've got Lidarr configured exactly like Radarr and Sonarr, using the same mount and it's just happens with Lidarr. I will investigate further.

**Comment by diegomontanaduarte** [comment]
The issue was related with the WinSCP encoding filename option that I have configured. Sorry about that, please close this one!
