### ISSUE TITLE
Unable to add Download Client with Privoxy

### ISSUE THREAD

**Issue by dimitrilctr** [linuxserver/docker-lidarr#77]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello :)

I already use Radarr/Readarr/Sonarr on my UNRAID' Server.
They are connected thought PRIVOXY on rTorrent. It works very well.

However, with the same configuration for lidarr as radarr/readarr/sonarr, it doesn't works.

**Here is my Docker configuration :**
------------------------------
![image](https://user-images.githubusercontent.com/35967750/171684405-cdf433ce-0ed3-430d-9f4c-df510ba5c887.png)

**My proxy setup :** (Who works on Radarr/Sonarr)
------------------------------
![image](https://user-images.githubusercontent.com/35967750/171684700-47cf3617-01d8-4c54-8b50-602934f6aa1f.png)

**The error when i'm trying to add rTorrent as Download Client :**
------------------------------
![image](https://user-images.githubusercontent.com/35967750/171684876-0bb44ce0-8cc8-47fd-8d03-44a18776364c.png)

## Expected Behavior
Privoxy on Sonarr expected to connected with rTorrent

## Current Behavior
Impossible to add Download Client

## Environment
**OS:** UNRAID
**CPU architecture:** x86_64/
**How docker service was installed:** By default on UNRAID
[Lidarr.debug.txt](https://github.com/linuxserver/docker-lidarr/files/8826036/Lidarr.debug.txt)

**Comment by Roxedus** [comment]
Can only guess with vital information unnecessary blured.
