### ISSUE TITLE
[BUG] Container tag 8.1.2135 should not exist

### ISSUE THREAD

**Issue by Skaronator** [linuxserver/docker-lidarr#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using Renovate App to update my container image tags. Renovate search for existing container image tags and update them accordingly.

Current version is [1.2.6](https://github.com/linuxserver/docker-lidarr/releases/tag/1.2.6.3313-ls127)

But on the container registry, 8.1.2135 exists as you can see:

```
$ docker pull ghcr.io/linuxserver/lidarr:8.1.2135
8.1.2135: Pulling from linuxserver/lidarr
Digest: sha256:8455e2c2f3a7e0fb56ab4de6be924d81aa441bfe9a740cf110d46b25a39b42ba
Status: Downloaded newer image for ghcr.io/linuxserver/lidarr:8.1.2135
ghcr.io/linuxserver/lidarr:8.1.2135
```

This throws off Renovate as you can see here: https://github.com/Skaronator/k8s-homelab/pull/36

### Expected Behavior

ghcr.io/linuxserver/lidarr:8.1.2135 should not exist when the current version is 1.2.6

### Steps To Reproduce

1. docker pull ghcr.io/linuxserver/lidarr:8.1.2135
2. Image gets pulled

### Environment

```markdown
- OS: Debian
- How docker service was installed: I'm not using docker. I use cri-o in Kubernetes.
```

### CPU architecture

x86-64

### Docker creation

```bash
If you're really curious: https://github.com/Skaronator/k8s-homelab/tree/main/download/lidarr
```

### Container logs

```bash
N/A
```

**Comment by Roxedus** [comment]
We do not delete tags. 

We have never supported following semver as a tagging scheme, as discussed in https://github.com/linuxserver/docker-prowlarr/issues/42
